name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extrair versão do package.json
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build e push da imagem Docker
        run: |
          IMAGE="ghcr.io/${{ secrets.GHCR_USERNAME }}/leopbrito-strapi:${{ steps.version.outputs.VERSION }}"
          echo "Iniciando o build da imagem"
          docker build -t $IMAGE -f Dockerfile.prod .
          docker push $IMAGE